#!/usr/bin/env python
# encoding: utf8

import requests
import docopt
import os
import subprocess

# You may want to change these.
myDir = os.environ['HOME'] + '/Desktop/'    # directory for HTML file
browser = 'com.apple.Safari'                # browser bundle identifier

usage = '''Usage: ipic (-i | -m | -a | -f | -t | -b | -n | -h) SEARCHTERM
  
Generate and open a web page of thumbnail images and links to larger images
for items in the iTunes/App/Mac App Stores.

Options:
  -i      iOS app
  -m      Mac app
  -a      album
  -f      movie (film)
  -t      TV show
  -b      book
  -n      audiobook (narration)
  -h      show this help message

Only one option is allowed. The HTML file for the generated web page is
saved on your Desktop.'''

# Handle the command line.
args = docopt.docopt(usage)
searchterm = args['SEARCHTERM']
if args['-i']:
  size = 512
  media = 'software'
  entity = 'software'
  name = 'trackName'
elif args['-m']:
  size = 512
  media = 'software'
  entity = 'macSoftware'
  name = 'trackName'
elif args['-a']:
  size = 600
  media = 'music'
  entity = 'album'
  name = 'collectionName'
elif args['-f']:
  size = 600
  media = 'movie'
  entity = 'movie'
  name = 'trackName'
elif args['-t']:
  size = 600
  media = 'tvShow'
  entity = 'tvSeason'
  name = 'collectionName'
elif args['-b']:
  size = 600
  media = 'ebook'
  entity = 'ebook'
  name = 'trackName'
elif args['-n']:
  size = 600
  media = 'audiobook'
  entity = 'audiobook'
  name = 'collectionName'
else:
  size = 600
  media = ''
  entity = ''
  name = ''

# Make the iTunes search call and collect the thumbnail and large image URLs.
iURL = 'https://itunes.apple.com/search'
parameters = {'term': searchterm, 'media': media, 'entity': entity}
r = requests.get(iURL, params=parameters)
results = r.json()['results']
turls = [ x['artworkUrl100'] for x in results ]
burls = [ x.replace('100x100', '{0}x{0}'.format(size)) for x in turls ]
names = [ x[name] for x in results ]

# Construct the HTML.
linkFmt = '<a href="{1}"><img src="{0}" alt="{2}", title="{2}" /></a>'
links = [linkFmt.format(x, y, z.encode('utf8'))
          for x, y, z in zip(turls, burls, names) ]
html = '''<html>                                                        <head><title>{0} pictures</title></head>
<body>
<h1>“{0}” pictures</h1>
{1}
</body>
</html>'''.format(searchterm, '\n'.join(links))

# Create an HTML file and open it.
htmlFile = myDir + searchterm + '.html'
with open(htmlFile, 'w') as f:
  f.write(html)

subprocess.check_call(['open', '-b', browser, htmlFile])
